let x = 7;
let y = 10;
console.log(x > y);
console.log(x >= y);
console.log(x < y);
console.log(x <= y);
console.log(x == y);
console.log(x === y);
console.log(x != y);
console.log(x !== y);
